### Build and push with following command:
# for label in 4 5 6 latest;do sed -e 's!__LABEL__!'$label'!' Dockerfile.tmpl >Dockerfile;docker build -t "docker.io/smoebody/dev-nodejs:${label}" .;docker --config ~/.docker_smoebody push "docker.io/smoebody/dev-nodejs:${label}";done
### install node ###
FROM node:__LABEL__
MAINTAINER ulf.seltmann@metaccount.de
VOLUME ["/app"]
ENTRYPOINT ["/docker/entrypoint"]
CMD ["run"]

# adding essentials
RUN apt-get update \
 && apt-get -y dist-upgrade \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y wget less vim locales graphicsmagick

ENV APP_HOME=/app \
	APP_USER=dev

ADD assets /docker
RUN chmod 755 /docker/init docker/entrypoint \
 && /docker/init \
 && rm -rf /docker/build
