#!/bin/bash

DOCKERHOST=$(ip route show | grep -e ^default | awk -F" " '{ print $3 }')

##
## setup defaults
##
SETUP_DIR="/docker/setup"

LOG_DIR="/var/log"

_setupRuntime() {
    # set up what has to be set up
    for i in `ls -A ${SETUP_DIR}`; do
        if [ "$i" == ".keepme" ];then continue;fi
        echo "Setting up $i..."
        source "${SETUP_DIR}/$i"
    done
}

echo "Setting up runtime environment..."
_setupRuntime

case "$1" in
    run)
        echo "Starting npm ..."
        exec su ${APP_USER} -c "cd ${APP_HOME};npm start"
        ;;
    *)
        exec su ${APP_USER} -c "cd ${APP_HOME};$@"
        fi;
        ;;
esac

exit 0
